name: learn-github-actions
on: 
  pull_request:
  workflow_dispatch:
jobs: 
  test:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
    - uses: actions/github-script@v7
      with:
        script: |
          const repos = [
          {
            name: "facebook.react",
            url: "https://github.com/facebook/react",
            mentorScore: 789,
            delta: 13,
            anomalies: [
              {
                id: "192 (0)",
                priority: "Critical",
                age: "1M",
                controlExpression: "expr"
              },
              {
                id: "169 (0)",
                priority: "High",
                age: "1Y",
                controlExpression: "expr"
              },
              {
                id: "169 (0)",
                priority: "Low",
                age: "1Y",
                controlExpression: "expr"
              },
              {
                id: "169 (0)",
                priority: "Medium",
                age: "1Y",
                controlExpression: "expr"
              }
            ]
          }];
          function createRow(anomaly){
            const {id, priority, age, controlExpression} = anomaly
            return `
          <tr>
            <td>${id}</td>
            <td>${getPriorityLevel(priority)}</td>
            <td>${age}</td>
            <td><code>${controlExpression}</code></td>
          </tr>
            `
          }
          function getPriorityLevel(priority){
            switch(priority){
              case "Critical":
                return "🔴 Critical"
              case "High":
                return "🟠 High"
              case "Medium":
                return "🟡 Medium"
              default:
                return "🟢 Low"
            }
          }

          function generateMarkdown(repos){
            let reportData = ""
            repos.forEach((repo) => {
              const {name, url, mentorScore, delta, anomalies} = repo
              const deltaColor = delta < 0 ? "⬇️" : "⬆️"
              const formatedDelta = delta < 0 ? delta : `+${delta}`
              reportData += `
          ### [${name}](${url}) -- Mentor Score: ${mentorScore} <span style="color: ${deltaColor}">(${formatedDelta})</span>
          <details>
          <summary>Anomalies</summary>

          <table>
            <thead>
              <tr>
                <th>Id</th>
                <th>Priority</th>
                <th>Age</th>
                <th>Control Expression</th>
              </tr>
            </thead>
            <tbody>
          ${generateAnomaliesRows(anomalies)}
            </tbody>
          </table>

          </details>
          `             
            })
            return reportData
          }

          function generateAnomaliesRows(anomalies){
            let reportData = ""
            anomalies.forEach(anomaly => {
              reportData += `${createRow(anomaly)}`
            })
            return reportData
          }

          const markdown = generateMarkdown(repos)

          github.rest.pulls.update({
            pull_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: markdown
          })