name: learn-github-actions
on: 
  pull_request:
  workflow_dispatch:
jobs: 
  test:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
    - uses: actions/github-script@v7
      with:
        script: |
          const repos = [
          {
            name: "facebook.react",
            url: "https://github.com/facebook/react",
            mentorScore: 789,
            delta: 13,
            anomalies: [
              {
                id: "192 (0)",
                priority: "Critical",
                age: "1M",
                controlExpression: "expr"
              },
              {
                id: "169 (0)",
                priority: "Critical",
                age: "1Y",
                controlExpression: "expr"
              }
            ]
          }];
          function createRow(id, priority, age, expr){
            return `
              <tr>
                <td>${id}</td>
                <td>${priority}</td>
                <td>${age}</td>
                <td>${expr}</td>
              </tr>
            `
          }

          function generateMarkdown(repos){
            let reportData = ""
            repos.forEach((repo) => {
              const {name, url, mentorScore, delta, anomalies} = repo
              reportData += `
                ### [${name}](${url}) -- Mentor Score: ${mentorScore} (${delta}) 
                <summary>Anomalies</summary>

                  <table>
                    <thead>
                      <tr>
                        <th align="left">Id</th>
                        <th align="right">Priority</th>
                        <th align="right">Age</th>
                        <th align="right">Control Expression</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>192 (0)</td>
                        <td>Critical</td>
                        <td>1M</td>
                        <td>expr</td>
                      </tr>
                      <tr>
                        <td>196 (6)</td>
                        <td>Critical</td>
                        <td>1Y</td>
                        <td>new expr</td>
                      </tr>
                    </tbody>
                  </table>

                  </details>
              `             
            })
            return reportData
          }

          const markdown = generateMarkdown(repos)

          github.rest.pulls.update({
            pull_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: markdown
          })